import buttonClass from './button';
import {newAdmin} from './admin';
import { importStudents, importTeachers, importUsers } from './connectToFirebase';
import { formDisplay } from './loginForm';
importUsers();
importStudents();
importTeachers();
buttonClass();
//formDisplay();
newAdmin('admin','admin');