import buttonClass from './button';
import {newAdmin} from './admin';
import { importCourses, importStudents, importTeachers, importUsers } from './connectToFirebase';
import { formDisplay } from './loginForm';
importUsers();
importStudents();
importTeachers();
importCourses();
buttonClass();
//formDisplay();
//newAdmin('admin','admin');